CREATE TRIGGER TR_HH
ON dbo.DON_GIA_HANG_HOA
FOR UPDATE
AS
IF UPDATE (GIA_DGHH)
BEGIN
UPDATE dbo.DM_HANG_HOA
SET dbo.DM_HANG_HOA.DONGIAHIENHANH = DON_GIA_HANG_HOA.GIA_DGHH
FROM dbo.DON_GIA_HANG_HOA INNER JOIN dbo.DM_HANG_HOA 
ON dbo.DM_HANG_HOA.ID_HANG_HOA=dbo.DON_GIA_HANG_HOA.ID_HH
END	




SELECT * FROM dbo.DM_HANG_HOA
INNER JOIN dbo.DON_GIA_HANG_HOA
ON dbo.DM_HANG_HOA.ID_HANG_HOA=dbo.DON_GIA_HANG_HOA.ID_HH



UPDATE ShowDonGia
SET ShowDonGia.DONGIAHIENHANH = ShowDonGia.GIA_DGHH

