//v70 © 2012 Tynt

Tynt=window.Tynt||[];
if(typeof Tynt.TCL=="undefined"){(function(){var fa=function(){var h=document,s=h.body,q=h.documentElement,V=eval("/*@cc_on!@*/false"),M=function(a,b){for(var c="",f=0;f<b;f++)c+=a;return c},w=M("a",50),u=(Tynt.e||"")+"ic.tynt.com",W=(Tynt.e||"")+"de.tynt.com/deb/",B=function(a){return a.replace(/^\s+|\s+$/g,"")},C=function(a,b){for(var c in a)if(a.hasOwnProperty(c))b[c]=a[c]},N=function(a){for(var b={},c=a.length,f=[],i=0;i<c;i++)if(!b[a[i]]){b[a[i]]=true;f.push(a[i])}return f},o,D;if(window.addEventListener){o=
function(a,b,c){a.addEventListener(b,c,false)};D=function(a,b,c){a.removeEventListener(b,c,false)}}else{o=function(a,b,c){a.attachEvent("on"+b,c)};D=function(a,b,c){a.detachEvent("on"+b,c)}}var X=function(a,b){var c=location.hostname.split("."),f=2;do{var i=c.slice(c.length-f,c.length).join(".");h.cookie=a+";path=/;domain=."+i+";"+b;f++}while(h.cookie.indexOf(a)==-1&&f<=c.length);if(h.cookie.indexOf(a)==-1)h.cookie=a+";path=/;"+b},E=function(a){h.readyState=="complete"?a():o(window,"load",function(){setTimeout(function(){if(typeof h.readyState==
"undefined"&&!V)h.readyState="complete";a()},10)})},n=function(a,b){var c=[],f=function(i,g){var d="http://"+i.replace("id="+w,"id="+N(Tynt).join("~"));if(d.indexOf(u+"/b/p?")>-1&&typeof Tynt.b=="string")d+="&b="+Tynt.b;var j=new Image(1,1);if(g)j.onerror=g;j.src=d};n=function(i,g){c.push([i,g])};E(function(){n=f;for(var i=0;i<c.length;i++)n(c[i][0],c[i][1]);c=null});n(a,b)},O=function(a){var b=[],c="",f;for(f in a)if(a.hasOwnProperty(f)){b.push(c,f,"=",a[f]);c="&"}return b.join("")},Q=function(a){for(var b=
0,c=a.length<100?a.length:100,f=0;f<c;f++)b+=a.charCodeAt(f);a=Math.floor(Math.random()*3844);c=Math.abs((new Date).getTime()-12281184E5);return P(c,7)+P((b+a)%3844,2)},R=function(a){if(a<62)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);else{var b=Math.floor(a/62);a=a-b*62;return b>=62?R(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)}},
P=function(a,b){var c=R(a);return M("0",b-c.length)+c},S=B((h.title||location.hostname).toString()).replace(RegExp(location.hash,"g"),""),Y=function(){for(var a=h.getElementsByTagName("link"),b=0;b<a.length;b++)if(a[b].getAttribute("rel")&&a[b].getAttribute("rel").match("canonical")&&a[b].getAttribute("href")){a=a[b].getAttribute("href");b=location.protocol+"//"+location.host+location.pathname;var c=h.getElementsByTagName("base")[0];if(c)if(c=c.getAttribute("href"))b=c;if(!a.match(/^http/)){if(a.charAt(0)==
"/"){c=b.indexOf("/",9);if(c>-1)b=b.slice(0,c)}else{c=b.lastIndexOf("/");if(c>9)b=b.slice(0,c+1);else b+="/"}a=b+a}return a}return""},F=function(a){return a.replace(/^https?:\/\//,"")},Z=function(a,b){for(var c=b+"=",f=a.split(";"),i=0;i<f.length;i++){for(var g=f[i];g.charAt(0)==" ";)g=g.substring(1,g.length);if(g.indexOf(c)==0)return g.substring(c.length,g.length)}return null},$=function(){var a=Z(h.cookie,"tracertraffic"),b=encodeURIComponent(F(Y())),c=h.location.hash;c=/tynt=/.test(c)?c.match(/tynt=?([^?&$#]*)/)[1]:
false;var f=u+"/b/p?id="+w+(a?"&et="+a:"")+(c?"&a="+c:"")+"&ts="+(new Date).getTime(),i=f+(b?"&cu="+b:""),g=i+(h.referrer?"&r="+encodeURIComponent(F(h.referrer)):"");a=g+"&t="+encodeURIComponent(S);n(a,function(){n(g,function(){n(i,function(){n(f)})})})},aa=function(){E(function(){var a={async:"async",src:"http://"+[W,"v2?id=",N(Tynt).join("~"),"&r=",encodeURIComponent(F(h.referrer))].join("")},b=h.createElement("script");C(a,b);C(void 0,b.style);a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,
a)})},G=function(){var a=[];return function(b){for(var c=a.length-1;c>=0;c--)if(a[c]==b)return false;a.unshift(b);a.length>3&&a.pop();return true}},ba=G(),ca=G(),da=function(){var a,b=function(){window.removeEventListener("blur",b,false);H(a);return true};return function(c){a=c.target||c.srcElement;window.removeEventListener("blur",b,false);if(a.nodeName=="IMG"&&a.parentNode.nodeName!="A"){window.addEventListener("blur",b,false);setTimeout(function(){h.removeEventListener("blur",b,false)},1E4)}return true}}(),
T=function(a){H(a.target||a.srcElement,true)},x,U=function(a){a=a.target||a.srcElement;x=a.nodeName=="IMG"?a:null},I=function(){var a=function(d){return typeof d.pageX=="number"?{x:d.pageX-(q.scrollLeft?q.scrollLeft:s.scrollLeft),y:d.pageY-(q.scrollTop?q.scrollTop:s.scrollTop)}:{x:d.clientX,y:d.clientY}},b=function(d){d=a(d);return d.x<=0||d.y<=0||d.x>=s.clientWidth||d.y>=s.clientHeight},c=function(d){d=a(d);return d.x<=0||d.y<=0||d.x>=q.clientWidth||d.y>=q.clientHeight},f=function(d){return d.target.nodeName==
"#document"},i=function(d){d=a(d);return d.x<=4||d.y<=4||d.x>=q.clientWidth-4||d.y>=q.clientHeight-4},g=function(d){g=navigator.userAgent.match("MSIE")?!h.compatMode||h.compatMode.indexOf("CSS")==-1?b:c:navigator.userAgent.match("Firefox")?f:i;g(d)};return function(d){if(x&&g(d)){H(x);x=null}return true}}(),ea=function(){function a(e,k){if(l(e))n(u+"/b/o?id="+w+(k?"&i=":"&l=")+encodeURIComponent(e)+"&ts="+(new Date).getTime())}function b(e){var k=e.target||e.srcElement;if(e.button<2)for(;k&&k!=h;){e=
k.href;if(k.nodeName=="A"&&e&&location.href.split("#")[0]!=e.split("#")[0]&&!/^javascript/i.test(e)){a(e);break}k=k.parentNode}}function c(){j&&a(j,true)}function f(e){if(e){e=e.target||e.srcElement;j=e.src||e.data||"flash";o(window,"blur",c)}}function i(){j=null;D(window,"blur",c)}function g(e){o(e,"mouseover",f);o(e,"mouseout",i)}function d(){j&&a(j,true)}var j,l=G();o(document,"mousedown",b);E(function(){for(var e=h.getElementsByTagName("iframe"),k=e.length-1;k>=0;k--){var p=e[k];if(p.src)g(p);
else if(p.name)try{o(frames[p.name].document,"mousedown",b)}catch(r){}}e=h.getElementsByTagName("object");for(k=e.length-1;k>=0;k--)g(e[k])});o(window,"beforeunload",d);o(window,"unload",d)},J;if(Tynt.c)J=function(){};else{Tynt.c=true;Tynt.m=Tynt.m||[];Tynt.n=Tynt.n||[];J=function(){var a=true,b,c=function(f,i){var g=w,d;d=(d=B(i))?d.split(/\s+/i).length:0;var j={id:g,wc:d,c:i,f:a?1:0,t:S};C(f,j);a=false;g=j.trace_type;delete j.trace_type;d=j.g;delete j.g;for(var l=[],e=["id","wc","f","w","h","t",
"c"],k=0;k<e.length;k++){var p=e[k],r=j[p];r&&l.push([p,encodeURIComponent(r).replace(/\'/g,"%27")]);delete j[p]}for(var m in j)if(j.hasOwnProperty(m))(e=j[m])&&l.push([m,encodeURIComponent(e).replace(/\'/g,"%27")]);m=[];k=2048-(("http://"+u+"/a/t/x#?").length+(3+d.length)+5);p=l.length;var v=r=0,t=0,K,y,L,z,A=0;for(m[A]={g:d,tp:null};r<p&&m.length<35;){K=l[r][0];j=l[r][1];L=K.length+2;y=k-L-v;if(y>0){e=j.substring(t,t+y);z=e.slice(-2).indexOf("%");if(z>-1){e=j.substring(t,t+y-2+z);v+=z+2}v+=e.length+
L;t+=e.length;m[A][K]=e}else v=k;if(v>=k){m[++A]={g:d,p:A};v=0}if(t>=j.length){r++;t=0}}m[0].tp=m.length;n(u+"/b/t/"+g+"?"+O(m[0]));for(d=1;d<m.length;d++)n(u+"/b/x/"+g+"?"+O(m[d]))};/tynt=nout/.test(location.href)||ea();if(window.addEventListener){navigator.userAgent.match("Firefox/2")||s.addEventListener("copy",T,false);window.addEventListener("mousedown",U,false);window.addEventListener("dragleave",I,false);window.addEventListener("dragexit",I,false);h.addEventListener("contextmenu",da,false)}else{s.attachEvent("oncopy",
T);h.getElementsByTagName("html")[0].attachEvent("ondragleave",I);s.attachEvent("onmousedown",U)}if(h.cookie.indexOf("tracertraffic=")!=-1)if(!h.referrer||h.referrer.indexOf(location.host)==-1)X("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT");$();aa();return function(f,i){if(!h.getElementById("tyntSh")){var g,d,j;if(i)if(!h.selection||!h.selection.createRange){d=getSelection();j=d.rangeCount>0&&d.getRangeAt(0);g=d.toString()}else{d=h.selection.createRange();j=d.duplicate();g=d.text}var l=
f.src;if(l&&!g&&ca(l)){d={trace_type:3,g:Q(l),w:f.width,h:f.height};for(j=0;j<Tynt.n.length;j++)Tynt.n[j](d,l);c(d,l)}else if(g&&B(g).length&&f.nodeName!="TEXTAREA"&&f.nodeName!="INPUT"){l=ba(g);d={trace_type:1};if(l)b=Q(g);d.g=b;for(var e=true,k=0;k<Tynt.m.length;k++)e=e&&Tynt.m[k](d,g,j,l);l&&e&&c(d,g)}}}}}if(!(/tracer=test|tracer=no_tracing|disableTracer=/.test(location.href)||/disableTracer=y/.test(h.cookie)))var H=J()};Tynt.TCL=function(){document.body?fa():setTimeout(Tynt.TCL,300)}})();Tynt.TCL()};
